// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:a_terminal/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(LocalTermModelAdapter());
    registerAdapter(RemoteTermModelAdapter());
    registerAdapter(RemoteTermTypeAdapter());
    registerAdapter(SettingModelAdapter());
    registerAdapter(TermTypeAdapter());
    registerAdapter(ThemeModeAdapter());
  }
}
